version: '2'
services:
  backend:
    image: emiliyata/dart-sense-backend:v9
    ports:
      - "9000:9000"
    networks:
      - darts_network

  frontend:
    image: emiliyata/dart-sense-frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    expose:
      - '80'
    networks:
      - darts_network

  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: 'darts'
      MYSQL_USER: 'a4papep'
      MYSQL_PASSWORD: '1856'
      MYSQL_ROOT_PASSWORD: 'dartssense'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - darts_network

volumes:
  my-db:

networks:
  darts_network:
    driver: bridge
